testapp/config/routes.rb
Rails.application.routes.draw do
  get 'companys/index'

  resources :companys do
    collection do
      get :destroy_all
    end
  end

  root 'companys#index'
end

testapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

testapp/app/models/comp.rb
class Comp < ApplicationRecord
end

testapp/app/models/company.rb
class Company < ApplicationRecord
end

testapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

testapp/app/controllers/companys_controller.rb
class CompanysController < ApplicationController

  def index
    @companys = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    response = HTTParty.get('https://iextrading.com/api/1.0/stock/market/collection/list?collectionName=in-focus')
      comp = JSON.parse response.body
      id=0
      comp.each do |row|
        id+=1
        name=row['companyName'].inspect
        price=row['latestPrice'].inspect+'$'
        params[:company]= {"name"=>name, "price"=>price}
        @company = Company.new(params.require(:company).permit(:name, :price))
        @company.save
      end
  end

  def destroy_all
    @companys = Company.all
    @companys.destroy_all
    redirect_to "/companys"
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    redirect_to "/companys"
  end

end

testapp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def work
  end
end

testapp/app/helpers/application_helper.rb
module ApplicationHelper
end

testapp/app/helpers/companys_helper.rb
module CompanysHelper
end

testapp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

testapp/app/views/companys/index.html.erb
<center>

<h1>Топ компаний</h1>

  <p>
    <%= button_to 'Parse', companys_path %>
  </p>

<p>
  <%= button_to 'Show', companys_path, :method => :get%>
</p>

<p>
  <%= button_to 'Удалить всё', destroy_all_companys_path,
                :method => :get,
                data: { confirm: 'Произойдет очистка БД. Вы уверены?' } %>
</p>

<form id="myform" style="display: none">
<table id="tbshow" border="2" align="center">
  <tr>
    <th>Наименование</th>
    <th>Стоимость акций</th>
    <th></th>
  </tr>

  <% @companys.each do |company| %>
    <tr id="12">
      <td><%= company.name %></td>
      <td><%= company.price %></td>
      <td><%= button_to 'Удалить', company_path(company),
                      method: :delete,
                      data: { confirm: 'Вы уверены?' } %></td>
    </tr>
  <% end %>
</table>
</form>

  <script>
      window.onload = function() {
           if (document.getElementById('12').hidden==false)
              document.getElementById('myform').style.display='block';
      };
   </script>

</center>

testapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Тестовое задание</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body bgcolor="#FFA07A" text="black">
    <%= yield %>
  </body>
</html>

testapp/app/views/welcome/work.html.erb
<h1>Топ компаний</h1>


<%= form_with scope: :company, url: companys_path, local: true do |form| %>
  <p>
    <%= button_to 'Parse', companys_path %>
  </p>

<% end %>

<p>
  <%= button_to 'Show', companys_path, :method => :get %>
</p>


<table>
  <tr>
    <th>Наименование</th>
    <th>Стоимость акций</th>
    <th></th>
  </tr>

  <% @companys.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= company.price %></td>
      <td><%= button_to 'Удалить', company_path(company),
                        method: :delete,
                        data: { confirm: 'Вы уверены?' } %></td>
    </tr>
  <% end %>
</table>